language: php
php:
  - '7.1'
  - nightly

cache:
  - vendor

before_script:
  - phpenv config-rm xdebug.ini
  - composer install

script:
  - phpdbg -qrr vendor/bin/phpunit --bootstrap vendor/autoload.php tests
